#!/bin/bash
#
#     Copyright (C) 2018 KreAch3R
#
#     Licensed under the Apache License, Version 2.0 (the "License");
#     you may not use this file except in compliance with the License.
#     You may obtain a copy of the License at
#
#          http://www.apache.org/licenses/LICENSE-2.0
#
#     Unless required by applicable law or agreed to in writing, software
#     distributed under the License is distributed on an "AS IS" BASIS,
#     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#     See the License for the specific language governing permissions and
#     limitations under the License.

# Version: 0.1

# Variables for color output
green=$(tput setaf 2)
cyan=$(tput setaf 6)
red=$(tput setaf 1)
yellow=$(tput setaf 3)
reset=$(tput sgr0)

# Variables
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
jarfile=$(ls $DIR | grep uber-apk-signer-.*.jar)

# Check for at least 3 arguments, else abort
if (( $# < 3 )); then
    echo "${red}Illegal number of parameters!${reset}"
    echo "${red}You need to specify at least three arguments, -a APKFILE, -ks KEYSTOREFILE, --ksAlias KEYNAME${reset}"
    exit 1
fi

java -jar $jarfile --allowResign --skipZipAlign "$@"